config/routes.rb
Inclass::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/home', to: "static_pages#home"

  match '/help', to:"static_pages#help"

  match 'about', to: "static_pages/about"

  match 'contact', to: "static_pages/contact"
  

   root :to => 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  password_digest :string(255)

class User < ActiveRecord::Base 
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   validates :password, presence: true, length: { minimum: 6 }
   validates :password_confirmation, presence: true

   private 
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController <ApplicationController
	before_filter :signed_in_user
	def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
	end

	def destroy
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      # create an error message and re-render the sign form
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)  # get the user back to where he was or to the default page (whatever the default is)
    session.delete(:return_to)
  end
  def store_location # we need to know where the user was to be able to  get him back there. that's why we need to save that location
    session[return_to] = request.root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@micropost = current_user.microposts.build if signed_in?
  end

  def help
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :destroy] # make sure that the user is signed in 
	# before we proceed with edit or update. this will have to be verified before we enter into these two 
	#methods.
	before_filter :correct_user, only: [:edit, :update] #same thing here. we have to check if the
	# user is correct.
	before_filter :admin_user, only: :destroy

	def show
		@user = User.find(params[:id])
		@microposts = @user.microposts.paginate(page: params[:page])
	end

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user]) #user object that is passed. params saves us from specifying each attribute of user.
		if @user.save       # this will fail if the info entered do not match the validations
			flash[:success] = "Welcome to the inclass App!" # if the objects passes, send this on the screen
			                                                #  the message in the flash stays only before we reload.
			                                                # it is just a message to tell the user that they registered correctly but 
			                                                # you do not need to make this messafe stay. 
			redirect_to @user
		else    # if we have an error, have a new view of user with the parameters given on line 10
			render 'new' # ceci fait que nous voyions une nouvelle page qui contient l'ancienne information
			              # mais avec les erreurs faits. les messages des erreurs se trouvent dans un autre fichier.
		end
	end

	def edit
	end
	def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

	def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  private
  
  def correct_user
  	@user = User.find(params[:id])
  	redirect_to(root_path) unless current_user?(@user)
  end

  

  def admin_user
      redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end
	def current_user? (user)
		user == current_user
	end
	def signed_in?
		!current_user.nil?
	end
	def current_user=(user)
		@current_user = user
	end
	def current_user
		#return the current user or if the current user is false or nil, set it to that.
		#this is an if else statement in one line same as
		#if @current_user
			#@current_user
			#else
			#@current_user = User.find_by_remember_token(cookies[:remember_token])

		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end
	def signed_in_user
  	unless signed_in?
  		store_location
  	redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#Return the gravatar (http://gravatar.com/) fo the given User
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "inclass app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial inclass app | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  </html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%#=  gravatar_for current_user, size: 52 %> 
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %> 
</span>

app/views/shared/error_messages.html.erb
<!-- # <% if @user.errors.any? %>
#   <div id="error_explanation">
#     <div class="alert alert-error">
#       The form contains <%= pluralize(@user.errors.count, "error") %>.
#     </div>
#     <ul>
#     <% @user.errors.full_messages.each do |msg| %>
#       <li>* <%= msg %></li>
#     <% end %>
#     </ul>
#   </div>
# <% end %>
 -->

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
<head>
	<title>Ruby on Rails Tutorial inclass app | <%= yield(:title) %></title>
</head>
<body><h1>About Us<h1>
<p>
The <a href="http://Railstutorial.org/">Ruby on rails tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">RUby on Rails</a>. This
is the inclass application for the tutorial.
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<!DOCTYPE html>
<html>
<head>
	<title>Ruby on Rails Tutorial inclass app | <%= yield(:title) %></title>
</head>
<body>
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the inclass app at the
<a href="http://railstutorial.org/contact">contact page</a>
</p>
</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
<head>
	<title>Ruby on Rails Tutorial inclass app | <%= yield(:title) %></title>
</head>
<body>
<h1>Help</h1>
<p>Get help on the Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails tutorial book</a>.
</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
<head>
	<title>Ruby on Rails Tutorial inclass app | <%= yield (:title) %></title>
<head>
<body>
	<h1>Inclass</h1>
	<p>
		This is the home page for the 
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		inclass application.
	</p>
<body>
<html>
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 

	

app/views/users/_user.html.erb
    <li>
      <%#= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? and !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete, data: { confirm: "are you sure?" } %>
      <% end %>
    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1> Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>

app/views/users/show.html.erb
<% provide( :title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="span8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>